name: Render and Deploy Quarto site

on:
  push:
    branches:
      - main   # deploy when main branch changes
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repo
      - uses: actions/checkout@v3

      # Step 2: Setup Quarto
      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          quarto-version: '1.3.351' # or latest

      # Step 3: Render the site
      - name: Render site
        run: quarto render

      # Step 4: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages
          keep_files: false
