name: Quarto Publish

on:
  push:
    branches: main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.1'  # or latest stable
          
      - name: Cache Quarto
        uses: actions/cache@v4
        with:
          path: ~/.quarto
          key: ${{ runner.os }}-quarto-${{ hashFiles('_quarto.yml') }}
          restore-keys: |
            ${{ runner.os }}-quarto-

      - uses: quarto-dev/quarto-actions/setup@v2
      
      - name: Render Quarto Project
        run: quarto render

      - name: Setup Pages
        uses: actions/configure-pages@v5
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    needs: build-deploy
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
